//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agregaUsuario.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckIn
    {
        public int Id { get; set; }
        public int IdParkingLot { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsOpen { get; set; }
    
        public virtual ParkingLot ParkingLot { get; set; }
    }
}
