//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agregaUsuario.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dieta_materia
    {
        public int IdDieta { get; set; }
        public int IdMateria { get; set; }
        public double Cantidad { get; set; }
    
        public virtual dieta dieta { get; set; }
        public virtual materia_prima materia_prima { get; set; }
    }
}
