//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agregaUsuario.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.Orders = new HashSet<Order>();
            this.PriceLocationMenuItems = new HashSet<PriceLocationMenuItem>();
            this.Reservations = new HashSet<Reservation>();
            this.ShippingPolygons = new HashSet<ShippingPolygon>();
            this.MenuItems = new HashSet<MenuItem>();
            this.Promotions = new HashSet<Promotion>();
            this.PaymentTypes = new HashSet<PaymentType>();
        }
    
        public int Id { get; set; }
        public string LocationName { get; set; }
        public int IdRestaurant { get; set; }
        public string Telephone { get; set; }
        public string Telephone2 { get; set; }
        public string Telephone3 { get; set; }
        public string ContactName { get; set; }
        public string ContactName2 { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Address { get; set; }
        public string Image { get; set; }
        public string Times { get; set; }
        public int EstimatedTime { get; set; }
        public string ReservationTimes { get; set; }
        public string SendTimes { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public bool AllowsReservation { get; set; }
        public bool AllowsSending { get; set; }
        public bool AllowsPickup { get; set; }
        public bool AllowsEatHere { get; set; }
        public bool Enabled { get; set; }
        public double MinimumCost { get; set; }
        public Nullable<double> ShippingCost { get; set; }
        public string PickupTimes { get; set; }
        public Nullable<int> MaximunReservation { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceLocationMenuItem> PriceLocationMenuItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShippingPolygon> ShippingPolygons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuItem> MenuItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promotion> Promotions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentType> PaymentTypes { get; set; }
    }
}
