//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agregaUsuario.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class materia_prima
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materia_prima()
        {
            this.dieta_materia = new HashSet<dieta_materia>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClaveServidor { get; set; }
        public bool IsServerVersion { get; set; }
        public string Nombre { get; set; }
        public double Fosforo { get; set; }
        public double MateriaGrasa { get; set; }
        public double CenizaBruta { get; set; }
        public double FibraBruta { get; set; }
        public double ProteinaBruta { get; set; }
        public double MateriaSeca { get; set; }
        public double FND { get; set; }
        public double FAD { get; set; }
        public double LAD { get; set; }
        public double Calcio { get; set; }
        public double ParedVegetal { get; set; }
        public double Azucares { get; set; }
        public double CenizasInsolubles { get; set; }
        public double Almidon { get; set; }
        public double EnergiaBruta { get; set; }
        public Nullable<int> IdCliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dieta_materia> dieta_materia { get; set; }
    }
}
