//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agregaUsuario.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class encalientesdbEntities : DbContext
    {
        public encalientesdbEntities()
            : base("name=encalientesdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<CardType> CardTypes { get; set; }
        public virtual DbSet<CodeNumberConfirmed> CodeNumberConfirmeds { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<IngredientGroup> IngredientGroups { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<MenuItemType> MenuItemTypes { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderMenuItem> OrderMenuItems { get; set; }
        public virtual DbSet<OrderState> OrderStates { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<PriceLocationMenuItem> PriceLocationMenuItems { get; set; }
        public virtual DbSet<PrivilegeSet> PrivilegeSets { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<PromotionCode> PromotionCodes { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<ShippingPolygon> ShippingPolygons { get; set; }
        public virtual DbSet<ShippingPolygonPoint> ShippingPolygonPoints { get; set; }
        public virtual DbSet<ShippingType> ShippingTypes { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TypeCode> TypeCodes { get; set; }
        public virtual DbSet<TypePromotion> TypePromotions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserAddress> UserAddresses { get; set; }
        public virtual DbSet<UserRate> UserRates { get; set; }
    }
}
