//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agregaUsuario.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sistemadietasEntities5 : DbContext
    {
        public sistemadietasEntities5()
            : base("name=sistemadietasEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<dieta> dietas { get; set; }
        public virtual DbSet<dieta_materia> dieta_materia { get; set; }
        public virtual DbSet<direccion> direccions { get; set; }
        public virtual DbSet<materia_prima> materia_prima { get; set; }
        public virtual DbSet<necesidadfisiologica> necesidadfisiologicas { get; set; }
        public virtual DbSet<tipoanimal> tipoanimals { get; set; }
    }
}
