//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agregaUsuario.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class necesidad_fisiologica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public necesidad_fisiologica()
        {
            this.tipo_animal = new HashSet<tipo_animal>();
        }
    
        public int Id { get; set; }
        public double VitaminaD { get; set; }
        public double VitaminaA { get; set; }
        public double VitaminaE { get; set; }
        public double P { get; set; }
        public double EM { get; set; }
        public double Ca { get; set; }
        public double Na { get; set; }
        public double Mg { get; set; }
        public double PM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipo_animal> tipo_animal { get; set; }
    }
}
