//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agregaUsuario.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderMenuItems = new HashSet<OrderMenuItem>();
        }
    
        public int Id { get; set; }
        public int IdLocation { get; set; }
        public Nullable<int> IdUser { get; set; }
        public int IdOrderStatus { get; set; }
        public int IdPaymentType { get; set; }
        public string Description { get; set; }
        public double Total { get; set; }
        public Nullable<int> IdCard { get; set; }
        public string BillDescription { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime SendingTime { get; set; }
        public int EstimatedTime { get; set; }
        public bool Enabled { get; set; }
        public int ShippingTypeId { get; set; }
        public Nullable<int> UserAddressId { get; set; }
        public Nullable<int> ReservationId { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Location Location { get; set; }
        public virtual OrderState OrderState { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Reservation Reservation { get; set; }
        public virtual ShippingType ShippingType { get; set; }
        public virtual User User { get; set; }
        public virtual UserAddress UserAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMenuItem> OrderMenuItems { get; set; }
    }
}
