//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agregaUsuario.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceLocationMenuItem
    {
        public int IdLocation { get; set; }
        public int IdMenuItem { get; set; }
        public double Price { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual MenuItem MenuItem { get; set; }
    }
}
