//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agregaUsuario.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionCode
    {
        public int Id { get; set; }
        public int IdPromotion { get; set; }
        public string Code { get; set; }
        public bool Erasable { get; set; }
        public bool Enabled { get; set; }
    
        public virtual Promotion Promotion { get; set; }
    }
}
