//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agregaUsuario.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.CodeNumberConfirmeds = new HashSet<CodeNumberConfirmed>();
        }
    
        public int Id { get; set; }
        public int IdUser { get; set; }
        public System.DateTime ExpirationTime { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string AppVersion { get; set; }
        public string Token { get; set; }
        public string FacebookToken { get; set; }
        public bool Enabled { get; set; }
        public Nullable<int> DeviceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodeNumberConfirmed> CodeNumberConfirmeds { get; set; }
        public virtual Device Device { get; set; }
        public virtual User User { get; set; }
    }
}
