//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agregaUsuario.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingPolygonPoint
    {
        public int Id { get; set; }
        public int IdShippingPolygon { get; set; }
        public int ListIndex { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public bool Enabled { get; set; }
    
        public virtual ShippingPolygon ShippingPolygon { get; set; }
    }
}
